baseurl: ""
repository: jesserogers/jesserogers.github.io
exclude: ['README.md', vendor]
permalink: pretty
paginate: 6
paginate_path: "/journal/:num/"
highlighter: rouge
sass:
    sass_dir: ./assets/css
